# Worker name
name = "data-api"

# Entrypoint/path to the file that will be executed
main = "src/index.ts"

# Date in yyyy-mm-dd to determine which version of Workers runtime to use
# Details: https://developers.cloudflare.com/workers/platform/compatibility-dates/ 
compatibility_date = "2021-11-12"

# Deploy to `<NAME>.<SUBDOMAIN>.workers.dev` for testing?
# @default `true`
workers_dev = true

# Usage model for the Worker
# Details: https://developers.cloudflare.com/workers/platform/limits
usage_model = "bundled"

# List of routes to publish the Worker to
routes = [
	{ pattern = "*", zone_id = "CF_ZONE_ID" }
]


# Map of environment variables to set when deploying the Worker
# Not inherited. @default `{}`
[vars]
# Token lowest denom exponent. 1 CHEQ = 10^9 ncheq
TOKEN_EXPONENT = 9
# Standard Cosmosd SDK REST API endpoint for a node on target network
REST_API = "https://rpc.cheqd.net"
# GraphQL API endpoint for target network. Can be sourced from a BigDipper instance.
GRAPHQL_API = "https://explorer-gql.cheqd.io"


# KV Namespaces accessible from the Worker
# Details: https://developers.cloudflare.com/workers/learning/how-kv-works
# @default `[]`
# kv_namespaces = [{
#   binding = "KV_NAMESPACE",
#   id = "KV_NAMESPACE_ID",
#   preview_id = ""
#   }]


# Optional custom build step when using Wrangler CLI for build
# Details: https://developers.cloudflare.com/workers/wrangler/custom-builds/
# @default {}
[build]
  # Custom build command. On Linux and macOS, the command is executed in the `sh` shell and the `cmd` shell for Windows.
  # The `&&` and `||` shell operators may be used.
  command = ""
  # The directory in which the command is executed.
  cwd = ""
  # The directory to watch for changes while using `wrangler dev`, defaults to the current working directory
  watch_dir = ""

# Configuration options for local development via Wrangler
[dev]
  # IP address for the local dev server to listen on
  # @default `localhost`
  ip = "localhost"
  # Port for the local dev server to listen on
  # @default `3000`
  port = 3000
  # Protocol that local wrangler dev server listens to requests on
  # @default `http`
  local_protocol = "http"
  # Host to forward requests to. Defaults to host of first route of project
  host = ""


# List of data files that the Worker should be bound to. This is
# the legacy way of binding to a data file. ES module Workers should
# do proper module imports.
[data_blobs]
  DATA = ""
# Path to custom tsconfig (optional)
tsconfig = "./tsconfig.json"

# Minify before uploading?
minify = "false"

# Add polyfills for node builtin modules and globals?
node_compat = "false"
