name = "data-api"
type = "javascript"

account_id = ""
workers_dev = true
zone_id = ""
compatibility_date = "2022-03-16"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
